### ISSUE TITLE
Allow easily setting the hostname

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-collectd-signalfx#3]
Setting the Hostname in `/etc/collectd/collectd.conf` is actually a little annoying to automate, since you have to make changes to _two_ lines:

```
FQDNLookup false
Hostname www.example.com
```

So it would be nice if this role had a task to do this automatically. Something like:

```yaml
- name: Set hostname in collectd configuration.
  lineinfile:
    dest: /etc/collectd/collectd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "{{ item.insertbefore | default('') }}"
  with_items:
    - regexp: "^FQDNLookup .+$"
      line: "FQDNLookup false"
    - regexp: "^Hostname .+$"
      line: 'Hostname "{{ collectd_hostname }}"'
      insertbefore: "^FQDNLookup.+$"
  when: collectd_hostname
  notify: restart collectd
```

Then you can just add `collectd_hostname` to set a custom hostname.

Reverting to not use a hostname and use FQDN instead would of course require a manual reversion; I'm not too worried about that though.
